/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [DateValue]
      ,[ID]
      ,[Bandwidth]
      ,[HostName]
      ,[ConnectionDuration]
      ,[ConnectionType]
      ,[TotalBytesIn]
      ,[TotalBytesOut]
      ,[TransitionTechnology]
      ,[TunnelType]
      ,[UserActivityState]
      ,[UserName]
      ,[ClientExternalAddress]
      ,[ClientIPv4Address]
      ,[ClientIPv6Address]
      ,[Checksum]
  FROM [Monitoring].[dbo].[VPN_ConnectionPerDate]
  order by [DateValue] desc